# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/msm8998-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter cheeseburger dumpling,$(TARGET_DEVICE)),)

endif
